import { StyleSheet } from 'react-native';

import {
  PROFILE_GREETING_LINE_HEIGHT,
  PROFILE_HEADER_TEXT_HEIGHT,
  PROFILE_NAME_LINE_HEIGHT,
} from '../mainScreenLayoutConstants';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  mapWrapper: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 0,
    overflow: 'hidden',
  },
  sheetRestoreWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    zIndex: 7,
    alignItems: 'center',
  },
  sheetRestoreBtn: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  contentScroll: {
    position: 'absolute',
    left: 0,
    right: 0,
  },
  fixedHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(255,255,255,0.82)',
    paddingHorizontal: 20,
    paddingTop: 68,
    paddingBottom: 15,
    zIndex: 5,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 120,
    gap: 18,
  },
  dragHandleZone: {
    alignItems: 'center',
    paddingTop: 6,
    paddingBottom: 6,
  },
  dragHandle: {
    alignSelf: 'center',
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#e0e0e0',
    marginTop: 8,
    marginBottom: 4,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  profileBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  profileLabels: {
    justifyContent: 'center',
    flexShrink: 1,
  },
  profileIconShell: {
    width: PROFILE_HEADER_TEXT_HEIGHT,
    height: PROFILE_HEADER_TEXT_HEIGHT,
    borderRadius: PROFILE_HEADER_TEXT_HEIGHT / 2,
    backgroundColor: '#d8d8d8',
    justifyContent: 'center',
    alignItems: 'center',
  },
  greeting: {
    color: '#666666',
    fontSize: 13,
    fontWeight: '600',
    lineHeight: PROFILE_GREETING_LINE_HEIGHT,
  },
  userName: {
    color: '#171717',
    fontSize: 22,
    fontWeight: '800',
    lineHeight: PROFILE_NAME_LINE_HEIGHT,
  },
  supportButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#171717',
    justifyContent: 'center',
    alignItems: 'center',
  },
  heroCard: {
    backgroundColor: '#171717',
    borderRadius: 30,
    padding: 18,
    gap: 16,
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
  },
  heroTextBlock: {
    flex: 1,
    gap: 8,
  },
  heroEyebrow: {
    color: '#ffd54a',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1.1,
  },
  heroTitle: {
    color: '#ffffff',
    fontSize: 30,
    fontWeight: '800',
    lineHeight: 34,
  },
  heroSubtitle: {
    color: '#ffffff',
    fontSize: 14,
    lineHeight: 21,
    opacity: 0.8,
  },
  heroBadge: {
    width: 58,
    height: 58,
    borderRadius: 20,
    backgroundColor: '#ffd54a',
    justifyContent: 'center',
    alignItems: 'center',
  },
  heroBadgeLabel: {
    color: '#171717',
    fontSize: 16,
    fontWeight: '900',
  },
  mapCard: {
    height: 240,
    borderRadius: 24,
    backgroundColor: '#dfe7ef',
    overflow: 'hidden',
    position: 'relative',
    marginBottom: 16,
  },
  mapTopShade: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 54,
    backgroundColor: 'rgba(255, 255, 255, 0.18)',
  },
  mapMarkerPickup: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#171717',
    borderWidth: 5,
    borderColor: '#ffd54a',
  },
  mapMarkerDropoff: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#ffd54a',
    borderWidth: 5,
    borderColor: '#171717',
  },
  mapMarkerNearbyDriver: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#171717',
    borderWidth: 2.5,
    borderColor: '#FFD000',
    alignItems: 'center',
    justifyContent: 'center',
  },
  driverFoundPill: {
    position: 'absolute',
    bottom: 48,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#171717',
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.28,
    shadowRadius: 16,
    elevation: 12,
    zIndex: 99,
  },
  driverFoundPillText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  routeAnimatorOuter: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: 'rgba(255,255,255,0.95)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#171717',
  },
  routeAnimatorInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#171717',
  },
  mapTiltLayer: {
    position: 'absolute',
    left: 18,
    right: 18,
    top: 20,
    bottom: 20,
    borderRadius: 28,
    backgroundColor: '#f8fbff',
    transform: [{ rotate: '-8deg' }],
  },
  mapBlockLarge: {
    position: 'absolute',
    left: 26,
    top: 26,
    width: 92,
    height: 58,
    borderRadius: 18,
    backgroundColor: '#dde7f0',
    transform: [{ rotate: '-11deg' }],
  },
  mapBlockMedium: {
    position: 'absolute',
    right: 28,
    top: 54,
    width: 78,
    height: 52,
    borderRadius: 18,
    backgroundColor: '#d6e1eb',
    transform: [{ rotate: '10deg' }],
  },
  mapBlockSmall: {
    position: 'absolute',
    left: 54,
    bottom: 34,
    width: 120,
    height: 64,
    borderRadius: 22,
    backgroundColor: '#dfe9f2',
    transform: [{ rotate: '7deg' }],
  },
  mapRouteShadow: {
    position: 'absolute',
    left: 76,
    right: 58,
    top: 74,
    height: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(42, 93, 160, 0.18)',
    transform: [{ rotate: '16deg' }],
  },
  mapRouteLine: {
    position: 'absolute',
    left: 72,
    right: 56,
    top: 70,
    height: 6,
    borderRadius: 999,
    backgroundColor: '#3c79bf',
    transform: [{ rotate: '16deg' }],
  },
  mapRoadHorizontal: {
    position: 'absolute',
    top: 94,
    left: -24,
    right: 12,
    height: 26,
    backgroundColor: '#ffffff',
    transform: [{ rotate: '-14deg' }],
  },
  mapRoadVertical: {
    position: 'absolute',
    right: 88,
    top: -16,
    bottom: -24,
    width: 30,
    backgroundColor: '#ffffff',
    transform: [{ rotate: '18deg' }],
  },
  mapPinPrimary: {
    position: 'absolute',
    left: 132,
    top: 92,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#171717',
    borderWidth: 5,
    borderColor: '#ffd54a',
  },
  mapPinSecondary: {
    position: 'absolute',
    right: 46,
    top: 68,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#ffd54a',
    borderWidth: 5,
    borderColor: '#171717',
  },
  driverChip: {
    position: 'absolute',
    right: 16,
    top: 20,
    borderRadius: 999,
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  driverChipText: {
    color: '#171717',
    fontSize: 12,
    fontWeight: '700',
  },
  mapCarMarker: {
    position: 'absolute',
    left: '50%',
    top: '50%',
    marginLeft: -30,
    marginTop: -16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mapCarMarkerShadow: {
    position: 'absolute',
    bottom: -2,
    width: 54,
    height: 14,
    borderRadius: 999,
    backgroundColor: 'rgba(0, 0, 0, 0.16)',
  },
  mapCarMarkerBubble: {
    width: 76,
    height: 56,
    borderRadius: 22,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 6,
  },
  mapMiniCarLeft: {
    position: 'absolute',
    left: 34,
    top: 126,
    transform: [{ rotate: '-12deg' }, { scale: 0.72 }],
    opacity: 0.9,
  },
  mapMiniCarRight: {
    position: 'absolute',
    right: 18,
    bottom: 38,
    transform: [{ rotate: '10deg' }, { scale: 0.68 }],
    opacity: 0.85,
  },
  mapRadialRoot: {
    flex: 1,
    position: 'relative',
  },
  mapRadialDim: {
    backgroundColor: 'rgba(0,0,0,0.42)',
  },
  mapRadialHint: {
    position: 'absolute',
    bottom: 48,
    left: 24,
    right: 24,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.88)',
    zIndex: 12,
  },
  mapRadialHintLoading: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.72)',
  },
  // Modals
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  modalSheet: {
    width: '100%',
    backgroundColor: '#ffffff',
    borderRadius: 28,
    padding: 24,
    gap: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.2,
    shadowRadius: 24,
    elevation: 16,
  },
  modalHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#e0e0e0',
    alignSelf: 'center',
    marginBottom: 4,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#171717',
    textAlign: 'center',
  },
  modalAvatarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    marginTop: 4,
  },
  modalAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#ffd54a',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#999999',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  modalInput: {
    borderWidth: 1.5,
    borderColor: '#e8e8e8',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 13,
    fontSize: 15,
    fontWeight: '500',
    color: '#171717',
    backgroundColor: '#fafafa',
  },
  modalAddressRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#f7f7f7',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  modalAddressText: {
    flex: 1,
    fontSize: 14,
    color: '#555555',
    fontWeight: '500',
  },
  modalSaveBtn: {
    backgroundColor: '#171717',
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 4,
  },
  modalSaveBtnText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '800',
  },
  modalCancelBtn: {
    alignItems: 'center',
    paddingVertical: 14,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#e0e0e0',
  },
  modalCancelBtnText: {
    color: '#171717',
    fontSize: 14,
    fontWeight: '700',
  },
  supportModalIcon: {
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: '#f5f5f5',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: 4,
  },
  supportModalSubtitle: {
    fontSize: 14,
    color: '#888888',
    textAlign: 'center',
    lineHeight: 20,
  },
  supportOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 16,
    paddingHorizontal: 16,
    backgroundColor: '#f7f7f7',
    borderRadius: 16,
  },
  supportOptionText: {
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
    color: '#171717',
  },
  // Destination Card
  destinationCard: {
    backgroundColor: '#ffffff',
    borderRadius: 24,
    padding: 18,
    gap: 14,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.07,
    shadowRadius: 12,
    elevation: 4,
  },
  destinationOverlay: {
    position: 'absolute',
    top: 108,
    left: 20,
    right: 20,
    zIndex: 7,
  },
  destinationOverlayInner: {
    borderRadius: 26,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.74)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.55)',
    padding: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 22,
    elevation: 10,
  },
  destinationOverlaySearchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 10,
  },
  destinationSearchGroup: {
    borderRadius: 20,
    overflow: 'hidden',
    position: 'relative',
  },
  whereToRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#f2f2f2',
    minHeight: 48,
    paddingVertical: 14,
    paddingHorizontal: 16,
    position: 'relative',
  },
  whereToRowTop: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
  },
  whereToRowBottom: {
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#dcdcdc',
  },
  whereToRowActive: {
    backgroundColor: '#eef3f8',
  },
  whereToTriggerText: {
    color: '#aaaaaa',
    fontSize: 15,
    fontWeight: '500',
    flex: 1,
  },
  whereToTriggerTextFilled: {
    color: '#171717',
  },
  whereToInput: {
    color: '#171717',
    fontSize: 15,
    fontWeight: '500',
    flex: 1,
  },
  whereToBottomLine: {
    position: 'absolute',
    left: 44,
    right: 14,
    bottom: 7,
    height: 2,
    borderRadius: 999,
    backgroundColor: '#171717',
    opacity: 0.9,
  },
  whereToBottomLineFocused: {
    left: 0,
    right: 0,
  },
  searchConnector: {
    position: 'absolute',
    left: 17,
    top: 16,
    bottom: 16,
    width: 16,
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 2,
  },
  searchConnectorTopDot: {
    width: 12,
    height: 12,
    borderRadius: 999,
    backgroundColor: '#f4c430',
    borderWidth: 2,
    borderColor: '#171717',
  },
  searchConnectorLine: {
    width: 2,
    flex: 1,
    marginVertical: 4,
    backgroundColor: '#171717',
    borderRadius: 999,
  },
  searchConnectorBottomPinOuter: {
    width: 14,
    height: 14,
    borderRadius: 4,
    backgroundColor: '#171717',
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '45deg' }],
  },
  searchConnectorBottomPinInner: {
    width: 7,
    height: 7,
    borderRadius: 999,
    backgroundColor: '#f4c430',
  },
  searchActionRow: {
    marginTop: 10,
    marginLeft: 28,
    marginRight: 14,
    alignItems: 'flex-end',
  },
  nowBadge: {
    backgroundColor: '#171717',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 7,
    flexShrink: 0,
  },
  searchActionBadge: {
    minWidth: 78,
    alignItems: 'center',
    justifyContent: 'center',
  },
  nowText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
  },
  routeIssueText: {
    color: '#9a6b00',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 8,
    marginHorizontal: 6,
  },
  suggestionList: {
    borderRadius: 20,
    paddingHorizontal: 2,
    paddingVertical: 4,
    borderWidth: 1,
    overflow: 'hidden',
  },
  suggestionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  suggestionIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#f7f7f7',
    justifyContent: 'center',
    alignItems: 'center',
  },
  suggestionTextBlock: {
    flex: 1,
    gap: 2,
  },
  suggestionTitle: {
    color: '#171717',
    fontSize: 14,
    fontWeight: '700',
  },
  suggestionSubtitle: {
    color: '#9b9b9b',
    fontSize: 12,
    fontWeight: '500',
  },
  suggestionActionIcon: {
    transform: [{ rotate: '45deg' }],
  },
  suggestionDivider: {
    height: 1,
    backgroundColor: '#f1f1f1',
    marginLeft: 60,
    marginRight: 12,
  },
  addressList: {
    gap: 0,
  },
  addressItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 11,
  },
  addressIconHome: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#fff8e1',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addressIconWork: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#e8f4fd',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addressTextBlock: {
    flex: 1,
    gap: 1,
  },
  addressLabel: {
    color: '#171717',
    fontSize: 14,
    fontWeight: '700',
  },
  addressSub: {
    color: '#aaaaaa',
    fontSize: 12,
    fontWeight: '400',
  },
  addressAddButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#eef2f6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addressPlusHorizontal: {
    position: 'absolute',
    width: 12,
    height: 2,
    borderRadius: 999,
    backgroundColor: '#65707d',
  },
  addressPlusVertical: {
    position: 'absolute',
    width: 2,
    height: 12,
    borderRadius: 999,
    backgroundColor: '#65707d',
  },
  addressText: {
    color: '#171717',
    fontSize: 15,
    fontWeight: '600',
  },
  addressDivider: {
    height: 1,
    backgroundColor: '#f0f0f0',
    marginLeft: 48,
  },
  // Service Cards
  serviceRowHeader: {
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 12,
    marginTop: 4,
  },
  serviceRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  serviceCard: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 8,
    alignItems: 'center',
    gap: 6,
    borderWidth: 2,
    borderColor: '#FFD000',
    minHeight: 148,
    justifyContent: 'center',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  serviceCardActive: {
    backgroundColor: '#FFD000',
    borderWidth: 0,
    shadowColor: '#c8880a',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 12,
  },
  serviceCardDisabled: {
    backgroundColor: '#fafafa',
    borderColor: '#e8e8e8',
    shadowOpacity: 0.04,
    elevation: 1,
    opacity: 0.6,
  },
  serviceCarImageWrap: {
    width: 76,
    height: 52,
    marginBottom: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  serviceCarImage: {
    width: '100%',
    height: '100%',
  },
  serviceDiscountPill: {
    backgroundColor: '#f0f0f0',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  serviceDiscountPillActive: {
    backgroundColor: 'rgba(0,0,0,0.14)',
  },
  serviceDiscountPillDisabled: {
    backgroundColor: '#ececec',
    paddingHorizontal: 4,
  },
  serviceDiscountText: {
    color: '#888888',
    fontSize: 10,
    fontWeight: '700',
  },
  serviceDiscountTextActive: {
    color: '#000000',
    fontWeight: '800',
  },
  serviceDiscountTextDisabled: {
    color: '#aaaaaa',
  },
  serviceDiscountTextComingSoon: {
    fontSize: 9,
    fontWeight: '800',
    textAlign: 'center',
    lineHeight: 12,
  },
  serviceTitle: {
    color: '#171717',
    fontSize: 14,
    fontWeight: '800',
  },
  serviceTitleActive: {
    color: '#000000',
    fontWeight: '900',
  },
  serviceTitleDisabled: {
    color: '#aaaaaa',
  },
  serviceSubLabel: {
    color: '#999999',
    fontSize: 11,
    fontWeight: '500',
    textAlign: 'center',
  },
  serviceSubLabelActive: {
    color: '#1a1a1a',
    fontWeight: '600',
  },
  serviceSubLabelDisabled: {
    color: '#cccccc',
  },
  // Promotional Card
  promoCard: {
    flexDirection: 'row',
    borderRadius: 20,
    overflow: 'hidden',
    marginBottom: 20,
    backgroundColor: '#f5f5f5',
    minHeight: 140,
  },
  promoContent: {
    flex: 1,
    padding: 20,
    justifyContent: 'center',
    gap: 12,
  },
  promoTitle: {
    fontSize: 17,
    fontWeight: '800',
    lineHeight: 22,
    color: '#171717',
  },
  promoButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#FFD000',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 12,
  },
  promoButtonText: {
    color: '#000000',
    fontSize: 14,
    fontWeight: '800',
  },
  promoIllustration: {
    width: 120,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  promoBox1: {
    position: 'absolute',
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: '#FFD000',
    opacity: 0.35,
    top: 24,
    right: 16,
  },
  promoBox2: {
    position: 'absolute',
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#4a90e2',
    opacity: 0.4,
    bottom: 32,
    right: 28,
  },
  promoBox3: {
    position: 'absolute',
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: '#52b788',
    opacity: 0.45,
    top: 48,
    right: 8,
  },
  // Top Drivers Section
  topDriversSection: {
    marginBottom: 24,
  },
  topDriversHeader: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  topDriversTitle: {
    fontSize: 20,
    fontWeight: '800',
  },
  topDriversSub: {
    fontSize: 12,
    fontWeight: '500',
  },
  topDriversOverflow: {
    overflow: 'hidden',
    marginHorizontal: -20,
    paddingHorizontal: 0,
  },
  topDriversScroll: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 20,
  },
  driverCard: {
    width: 150,
    borderRadius: 20,
    padding: 16,
    alignItems: 'center',
    gap: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.10,
    shadowRadius: 10,
    elevation: 5,
    borderWidth: 1.5,
    borderColor: 'rgba(0,0,0,0.05)',
  },
  driverAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 2,
  },
  driverName: {
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
  },
  driverRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  driverRatingText: {
    fontSize: 13,
    fontWeight: '700',
  },
  driverTripsBadge: {
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  driverTripsText: {
    fontSize: 11,
    fontWeight: '600',
  },
  driverBookBtn: {
    marginTop: 4,
    backgroundColor: '#FFD000',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 8,
    width: '100%',
    alignItems: 'center',
  },
  driverBookBtnText: {
    color: '#000000',
    fontSize: 12,
    fontWeight: '800',
  },
  // Tab Bar Styles with Notch
  tabBar: {
    position: 'absolute',
    bottom: 16,
    left: 20,
    right: 20,
    height: 68,
    borderRadius: 28,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingBottom: 4,
    zIndex: 6,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.82)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.6)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.10,
    shadowRadius: 12,
    elevation: 8,
  },
  tabItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  tabItemCenter: {
    flex: 1,
  },
  tabLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#aaaaaa',
  },
  tabLabelActive: {
    color: '#1a1a1a',
    fontWeight: '700',
  },
  tabSectionLabel: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    marginBottom: 6,
    marginTop: 12,
    marginLeft: 4,
  },
  // Ride Detail Modal
  rideDetailOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  rideDetailSheet: {
    width: '100%',
    borderRadius: 28,
    padding: 24,
    alignItems: 'center',
    gap: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.25,
    shadowRadius: 24,
    elevation: 16,
  },
  rideDetailHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#ddd',
    marginBottom: 8,
  },
  rideDetailIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  rideDetailAvatarText: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  rideDetailRoute: {
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  rideDetailArrowRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    width: '60%',
    marginVertical: 2,
  },
  rideDetailLine: {
    flex: 1,
    height: 1,
  },
  rideDetailDivider: {
    height: 1,
    width: '100%',
    marginVertical: 12,
  },
  rideDetailMeta: {
    width: '100%',
    gap: 12,
  },
  rideDetailMetaItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  rideDetailMetaLabel: {
    fontSize: 13,
    fontWeight: '500',
  },
  rideDetailMetaValue: {
    fontSize: 14,
    fontWeight: '700',
  },
  rideDetailStars: {
    flexDirection: 'row',
    gap: 2,
  },
  rideDetailBookBtn: {
    marginTop: 16,
    backgroundColor: '#FFD000',
    borderRadius: 16,
    paddingVertical: 14,
    width: '100%',
    alignItems: 'center',
  },
  rideDetailBookBtnText: {
    color: '#000000',
    fontSize: 15,
    fontWeight: '800',
  },
  tabCard: {
    borderRadius: 18,
    overflow: 'hidden',
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    shadowRadius: 6,
    elevation: 2,
  },
  tabDivider: {
    height: 1,
    marginHorizontal: 16,
  },
  // Ride history
  rideHistoryItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 12,
  },
  rideHistoryIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rideHistoryAvatarText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  rideHistoryBody: {
    flex: 1,
    gap: 2,
  },
  rideHistoryRoute: {
    fontSize: 14,
    fontWeight: '700',
  },
  rideHistoryMeta: {
    fontSize: 12,
    fontWeight: '500',
  },
  rideHistoryStars: {
    flexDirection: 'row',
    gap: 2,
    marginTop: 2,
  },
  rideHistoryPrice: {
    fontSize: 14,
    fontWeight: '700',
  },
  rideViewPill: {
    borderRadius: 20,
    paddingHorizontal: 11,
    paddingVertical: 5,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#FFB800',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 3,
  },
  rideViewPillText: {
    color: '#000000',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  // Favourites
  favItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 12,
  },
  favIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
  },
  favBody: {
    flex: 1,
    gap: 2,
  },
  favTitle: {
    fontSize: 14,
    fontWeight: '700',
  },
  favSubtitle: {
    fontSize: 12,
    fontWeight: '500',
  },
  // Settings
  settingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 15,
    gap: 14,
  },
  settingsRowLabel: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
  },
  settingsRowRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  settingsRowValue: {
    fontSize: 14,
    fontWeight: '500',
  },
  notifRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    gap: 12,
  },
  notifRowLabel: {
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 2,
  },
  notifRowSub: {
    fontSize: 12,
    fontWeight: '500',
  },
  settingsSignOut: {
    marginTop: 20,
    marginHorizontal: 0,
    borderRadius: 18,
    borderWidth: 1,
    paddingVertical: 16,
    alignItems: 'center',
  },
  settingsSignOutText: {
    fontSize: 15,
    fontWeight: '700',
  },
  // Edit Profile screen (reference layout)
  editProfileRoot: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  editProfileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 56,
    paddingHorizontal: 4,
    paddingBottom: 12,
    backgroundColor: '#ffffff',
  },
  editProfileHeaderSide: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  editProfileHeaderTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: '800',
    color: '#171717',
  },
  editProfileScroll: {
    flex: 1,
  },
  editProfileScrollContent: {
    paddingHorizontal: 22,
    paddingBottom: 40,
    paddingTop: 4,
  },
  profileViewScrollContent: {
    paddingHorizontal: 22,
    paddingBottom: 40,
    paddingTop: 4,
  },
  profileViewSectionHeadingWrap: {
    marginBottom: 10,
    marginTop: 4,
  },
  profilePaymentSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
    marginTop: 4,
  },
  profileViewSectionTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#888888',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  profileViewSectionTitleFlex: {
    flex: 1,
  },
  profileAddCardIconBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#f0f0f0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileViewCard: {
    backgroundColor: '#fafafa',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 4,
    marginBottom: 20,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#eeeeee',
  },
  profileViewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    gap: 12,
  },
  profileViewRowTop: {
    alignItems: 'flex-start',
  },
  profileViewLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#171717',
    flexShrink: 0,
    width: 100,
  },
  profileViewValue: {
    flex: 1,
    fontSize: 15,
    fontWeight: '500',
    color: '#555555',
    textAlign: 'right',
  },
  profileViewValueMultiline: {
    textAlign: 'right',
  },
  profileViewDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: '#e8e8e8',
  },
  profilePaymentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
  },
  profilePaymentCardIcon: {
    width: 44,
    height: 28,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  profilePaymentVisa: {
    backgroundColor: '#1a1f71',
  },
  profilePaymentMc: {
    backgroundColor: '#eb001b',
  },
  profilePaymentCardIconText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  profilePaymentLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: '#171717',
  },
  profilePaymentSub: {
    fontSize: 12,
    color: '#888888',
    marginTop: 2,
  },
  profilePaymentDefaultBadge: {
    backgroundColor: '#fff8e1',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
    marginRight: 4,
  },
  profilePaymentDefaultText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#b8860b',
  },
  resetPasswordButton: {
    marginTop: 8,
    marginBottom: 24,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: '#171717',
    paddingVertical: 16,
    alignItems: 'center',
  },
  resetPasswordButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#171717',
  },
  signOutButton: {
    marginBottom: 32,
    borderRadius: 16,
    backgroundColor: '#171717',
    paddingVertical: 16,
    alignItems: 'center',
  },
  signOutButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ffffff',
  },
  addCardKb: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  addCardScrollContent: {
    flexGrow: 1,
    justifyContent: 'flex-end',
  },
  addCardSheet: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 24,
    paddingBottom: 36,
    gap: 10,
    maxHeight: '88%',
  },
  addCardPreview: {
    alignSelf: 'center',
    width: '92%',
    maxWidth: 400,
    aspectRatio: 1.586,
    maxHeight: 200,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#ffffff',
    marginBottom: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addCardPreviewImage: {
    width: '100%',
    height: '100%',
  },
  addCardRow: {
    flexDirection: 'row',
    gap: 12,
  },
  addCardRowField: {
    flex: 1,
  },
  editProfileAvatarWrap: {
    alignSelf: 'center',
    marginBottom: 28,
    width: 120,
    height: 120,
    position: 'relative',
  },
  editProfileAvatarImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#f0f0f0',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  editProfileAvatarCamera: {
    position: 'absolute',
    right: 2,
    bottom: 2,
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 4,
  },
  editProfileField: {
    marginBottom: 20,
  },
  editProfileHint: {
    fontSize: 12,
    lineHeight: 17,
    color: '#888888',
    marginTop: 8,
  },
  editProfileLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: '#171717',
    marginBottom: 8,
  },
  editProfileInput: {
    backgroundColor: '#f0f0f0',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    fontWeight: '500',
    color: '#4a4a4a',
  },
  editProfilePasswordRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f0f0f0',
    borderRadius: 16,
    paddingLeft: 16,
    paddingRight: 4,
  },
  editProfilePasswordInput: {
    flex: 1,
    backgroundColor: 'transparent',
    paddingHorizontal: 0,
    paddingVertical: 14,
  },
  editProfileEyeBtn: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  editProfilePhoneRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  editProfileCountryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#f0f0f0',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  editProfileCountryText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#4a4a4a',
  },
  editProfilePhoneInput: {
    flex: 1,
  },
  editProfilePickerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  editProfilePickerSheet: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 36,
  },
  editProfilePickerTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#171717',
    marginBottom: 8,
  },
  editProfilePickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#f0f0f0',
    gap: 12,
  },
  editProfilePickerCode: {
    fontSize: 16,
    fontWeight: '700',
    color: '#171717',
    width: 56,
  },
  editProfilePickerLabel: {
    flex: 1,
    fontSize: 15,
    color: '#666666',
  },
  fabHalo: {
    display: 'none',
    position: 'absolute',
    bottom: 36,
    left: '50%',
    marginLeft: -34,
    width: 68,
    height: 68,
    borderRadius: 34,
    backgroundColor: '#ffffff',
    zIndex: 8,
  },
  floatingButton: { display: 'none', position: 'absolute', bottom: 0, width: 0, height: 0, zIndex: 0 },
  plusButton: { width: 0, height: 0 },
  plusHorizontal: { width: 0, height: 0 },
  plusVertical: { width: 0, height: 0 },
});
